version: '3.9'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: docker.env
    networks:
      - local-network

  api:
    container_name: api
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: docker.env
    ports:
      - 8000:8000
      - 5678:5678
    networks:
      - local-network
    volumes:
      - .:/app
      - postgres_data:/var/lib/postgresql/data

    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"]

volumes: 
  postgres_data:
    driver: local

networks:
  local-network:
    name: local-network